import type { Stage } from '../types'
import { rankPlayers } from './tournament.ts'
import { activeTiebreaks } from './scoring.ts'
const safe=(value:unknown)=>typeof value==='string'&&/^[=+@\-\t\r]/.test(value)?`'${value}`:value
export function reportRows(stages:Stage[]){
  const summary:unknown[][]=[['阶段','选手','完成率合计','DX 合计','阶段排名','晋级状态','晋级依据']],songs:unknown[][]=[['阶段','选手','歌曲','谱面','完成率','DX 分']],ties:unknown[][]=[['阶段','加赛轮次','说明','选手','完成率','DX 分','有效性']]
  for(const stage of stages){const active=activeTiebreaks(stage);for(const p of rankPlayers(stage).players){summary.push([stage.name,p.name,p.score,p.dxScore,p.rank,stage.locked?(p.advanced?'晋级':'未晋级'):'未确认',active.some(r=>r.scores[p.id])?'原成绩 → 加赛完成率 → 加赛 DX':'完成率 → DX 分']);for(const song of stage.songs){const score=p.chartScores?.[song.id];songs.push([stage.name,p.name,song.name,song.difficulty,score?.score??'',score?.dxScore??''])}}for(const [i,r] of (stage.tiebreaks??[]).entries())for(const [id,score] of Object.entries(r.scores))ties.push([stage.name,i+1,r.note,stage.players.find(p=>p.id===id)?.name??id,score.score,score.dxScore,active.some(a=>a.id===r.id)?'有效':'仅存档'])}
  return {summary:summary.map(r=>r.map(safe)),songs:songs.map(r=>r.map(safe)),ties:ties.map(r=>r.map(safe))}
}
export async function exportWorkbook(stages:Stage[]){const xlsx=await import('xlsx'),rows=reportRows(stages),book=xlsx.utils.book_new();for(const [name,data] of [['排名与晋级',rows.summary],['逐曲成绩',rows.songs],['加赛记录',rows.ties]] as const){const sheet=xlsx.utils.aoa_to_sheet(data);sheet['!cols']=data[0].map(()=>({wch:22}));xlsx.utils.book_append_sheet(book,sheet,name)}xlsx.writeFile(book,'赛事报告.xlsx')}
export async function exportResultImage(stage:Stage,page=0){const ranked=rankPlayers(stage).players.filter(p=>p.rank!==null).sort((a,b)=>(a.rank??0)-(b.rank??0)),rows=ranked.slice(page*25,page*25+25);if(!rows.length)throw Error('暂无可导出的排名。');const canvas=document.createElement('canvas');canvas.width=1440;canvas.height=250+rows.length*72;const ctx=canvas.getContext('2d');if(!ctx)throw Error('浏览器不支持图片导出。');const gradient=ctx.createLinearGradient(0,0,1440,canvas.height);gradient.addColorStop(0,'#161616');gradient.addColorStop(1,'#080808');ctx.fillStyle=gradient;ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#fff';ctx.font='bold 48px sans-serif';ctx.fillText(stage.name,64,85,1280);ctx.font='24px sans-serif';ctx.fillStyle='#dedede';ctx.fillText(`${stage.locked?'已确认结果':'实时排名 · 尚未确认'}  |  ${page+1}/${Math.ceil(ranked.length/25)}  |  maimai Random Pro`,64,135);rows.forEach((p,i)=>{const y=215+i*72;ctx.fillStyle=i%2?'#252525':'#1c1c1c';ctx.fillRect(48,y-38,1344,60);ctx.fillStyle='#fff';ctx.font='26px sans-serif';ctx.fillText(`#${p.rank}`,70,y);ctx.fillText(p.name,170,y,460);ctx.fillText(`${p.score??'—'}%`,660,y);ctx.fillText(`DX ${p.dxScore??'—'}`,940,y);ctx.fillStyle='#ffffff';ctx.fillText(stage.locked?(p.advanced?'晋级':'未晋级'):'待确认',1200,y)});const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw Error('图片导出失败。');const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`赛事结果-${page+1}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
