import { useEffect, useState } from 'react'
import { checkpoint, listSnapshots, type Snapshot } from '../lib/snapshots'
import { validateStages } from '../lib/tournament'
import { applyRemote, save } from '../lib/storage'
import { useNotice } from './Notice'
import { publishRaffle } from '../store/raffleStore'
import { validateRaffle } from '../lib/raffle'
import { emptyCallboard, validateCallboard } from '../lib/callboard'
export default function BackupPanel(){const [items,setItems]=useState<Snapshot[]>([]),[busy,setBusy]=useState(false),notice=useNotice();useEffect(()=>{const refresh=()=>{void listSnapshots().then(setItems).catch(()=>notice('无法读取自动备份，请使用手动备份。'))};refresh();window.addEventListener('pro-backups',refresh);return()=>window.removeEventListener('pro-backups',refresh)},[notice]);return <section className="panel backup-panel content-panel"><div className="section-title"><h2>自动备份与恢复</h2><span className="tag">最近 10 次</span></div><p className="reading-copy">本设备保留最近 10 次快照；修改后自动保存。恢复前会保存当前状态，原有手动备份继续可用。</p><div className="backup-actions"><button disabled={busy} onClick={()=>{void checkpoint('手动快照').catch(()=>notice('快照保存失败。'))}}>立即保存快照</button></div><div className="snapshot-list">{items.map(item=><div className="snapshot-row row wrap" key={item.id}><div className="snapshot-info"><strong>{item.label}</strong><time>{new Date(item.time).toLocaleString('zh-CN')}</time></div><button disabled={busy} onClick={async()=>{if(!confirm('恢复此快照将替换当前赛事、抽奖、叫号与导播状态，并同步到其他设备。是否继续？'))return;setBusy(true);try{const tournament=item.data['maimai-pro-tournament'] as {stages:unknown}|undefined;if(tournament)validateStages(tournament.stages);const raffle=item.data['maimai-pro-raffle-control'];if(raffle)validateRaffle(raffle);const board=item.data['maimai-pro-callboard'];if(board)validateCallboard(board);await checkpoint('恢复快照前');for(const [key,value] of Object.entries({...item.data,'maimai-pro-callboard':board??emptyCallboard()})){applyRemote(key,value);if(!save(key,value))throw Error('数据保存失败，请保留快照并重试。')}publishRaffle();notice('快照已恢复。')}catch(e){notice(e instanceof Error?e.message:'恢复失败。')}finally{setBusy(false)}}}>恢复</button></div>)}</div>{!items.length&&<p className="hint">首次修改后将出现自动快照。</p>}</section>}
