import { useEffect, useRef, useState } from 'react'
import { Plus, Trash2, X } from 'lucide-react'
import type { Stage } from '../types'
import Select from './Select'
import ClickSpark from './ClickSpark'
export default function StageEditor({stages,started,currentStage,onSave,onClose}:{stages:Stage[];started:boolean;currentStage:string;onSave:(stages:Stage[])=>void;onClose:()=>void}) {
  const [draft,setDraft]=useState(()=>structuredClone(stages))
  const dialog=useRef<HTMLDialogElement>(null)
  const closeTimer=useRef<ReturnType<typeof setTimeout>>()
  useEffect(()=>{dialog.current?.showModal();return()=>clearTimeout(closeTimer.current)},[])
  const close=()=>{if(dialog.current?.classList.contains('is-closing'))return;dialog.current?.classList.add('is-closing');closeTimer.current=setTimeout(onClose,matchMedia('(prefers-reduced-motion: reduce)').matches?0:160)}
  const currentIndex=stages.findIndex(s=>s.id===currentStage)
  const update=(id:string,values:Partial<Stage>)=>setDraft(old=>old.map(s=>s.id===id?{...s,...values}:s))
  return <dialog ref={dialog} className="stage-dialog" aria-labelledby="stage-editor-title" onCancel={e=>{e.preventDefault();close()}}><form onSubmit={e=>{e.preventDefault();onSave(draft)}}><div className="section-title dialog-heading"><h2 id="stage-editor-title">自定义赛事</h2><button type="button" className="icon-button" aria-label="关闭赛事设置" onClick={close}><X size={22}/></button></div><div className="stage-config-list">{draft.map((s,i)=>{
    const readonly=started && (i<=currentIndex || s.locked)
    const later=draft.slice(i+1)
    return <section className="stage-config" key={s.id} style={{'--stage-index':i} as React.CSSProperties}><div className="section-title"><h3>阶段 {i+1}</h3>{readonly?<span className="tag">已锁定</span>:<button type="button" className="icon-button danger" aria-label={`删除阶段 ${i+1}`} disabled={draft.length===1 || !!s.players.length} onClick={()=>setDraft(draft.filter(v=>v.id!==s.id).map(v=>({...v,winnerStageId:v.winnerStageId===s.id?undefined:v.winnerStageId,loserStageId:v.loserStageId===s.id?undefined:v.loserStageId})))}><Trash2 size={18}/></button>}</div><div className="stage-config-grid"><label className="stage-name-field">阶段名称<input disabled={readonly} aria-label={`阶段 ${i+1} 名称`} value={s.name} maxLength={80} required onChange={e=>update(s.id,{name:e.target.value})}/></label><label>参赛人数<input disabled={readonly} aria-label={`阶段 ${i+1} 参赛人数`} type="number" min={1} max={10000} value={s.playerCount??32} onChange={e=>update(s.id,{playerCount:Number(e.target.value)})}/></label><label>歌曲数量<input disabled={readonly} aria-label={`阶段 ${i+1} 歌曲数量`} type="number" min={1} max={16} value={s.songCount??4} onChange={e=>update(s.id,{songCount:Number(e.target.value)})}/></label><label>排名方式<Select disabled={readonly} label={`阶段 ${i+1} 排名方式`} value={s.rankingMethod??'global'} options={[{value:'global',label:'全局排名'},{value:'group',label:'分组排名'}]} onChange={v=>update(s.id,{rankingMethod:v as Stage['rankingMethod']})}/></label>{s.rankingMethod==='group'?<><label>分组数量<input disabled={readonly} aria-label={`阶段 ${i+1} 分组数量`} type="number" min={1} max={64} value={s.groupCount??2} onChange={e=>update(s.id,{groupCount:Number(e.target.value),...(s.rankingMethod==='group'?{advanceCount:Number(e.target.value)*(s.advancePerGroup??1)}:{})})}/></label><label>每组晋级<input disabled={readonly} aria-label={`阶段 ${i+1} 每组晋级`} type="number" min={0} max={10000} value={s.advancePerGroup??1} onChange={e=>update(s.id,{advancePerGroup:Number(e.target.value),advanceCount:(s.groupCount??2)*Number(e.target.value)})}/></label></>:<label>晋级人数<input disabled={readonly} aria-label={`阶段 ${i+1} 晋级人数`} type="number" min={0} max={10000} value={s.advanceCount} onChange={e=>update(s.id,{advanceCount:Number(e.target.value)})}/></label>}<label>晋级阶段<Select disabled={readonly} label={`阶段 ${i+1} 晋级阶段`} value={s.winnerStageId??''} options={[{value:'',label:later.length?'下一主赛阶段':'结束赛事'},...later.filter(v=>v.id!==s.loserStageId).map(v=>({value:v.id,label:v.name}))]} onChange={v=>update(s.id,{winnerStageId:v||undefined})}/></label><label>败者组<Select disabled={readonly} label={`阶段 ${i+1} 败者组`} value={s.loserStageId??''} options={[{value:'',label:'不设置'},...later.filter(v=>v.id!==s.winnerStageId).map(v=>({value:v.id,label:v.name}))]} onChange={v=>update(s.id,{loserStageId:v||undefined})}/></label></div></section>
  })}</div><div className="dialog-actions"><button type="button" disabled={draft.length>=20} onClick={()=>setDraft([...draft,{id:crypto.randomUUID(),name:'新阶段',advanceCount:1,playerCount:8,rankingMethod:'global',groupCount:2,advancePerGroup:1,songCount:4,players:[],songs:[],groups:[],locked:false}])}><Plus size={18}/>添加阶段</button><div className="row"><button type="button" onClick={close}>取消</button><button type="submit" className="primary">保存赛制</button></div></div></form><ClickSpark/></dialog>
}
